Hw controllers add
margarita-ignatieva/cinema_shop pull request #9
Opened 2020-10-27 13:09 UTC by margarita-ignatieva

2020-10-27 13:34 UTC, gradiviro approved these changes

2020-10-27 14:18 UTC, KseniiaMakarova requested changes

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/controllers/OrderController.java
> +    private OrderMapper orderMapper;
add `final`

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/controllers/ShoppingCartController.java
> +    private ShoppingCartMapper shoppingCartMapper;
same

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/controllers/UserController.java
> +    private UserMapper userMapper;
same

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/dao/TicketDao.java
> +    Ticket getById(Long id);
do you use it?

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/dao/UserDao.java
> +    User getById(Long id);
```suggestion
    User get(Long id);
```
remember about uniform method names

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/model/dto/ShoppingCartResponseDto.java
> +    private Long userId;
aren't `cartId` and `userId` the same?

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/model/dto/UserResponseDto.java
> +    private String password;
let's not return secure data

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/service/TicketService.java
> +public interface TicketService {
do you need this service?

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/service/UserService.java
> +    User getById(Long id);
```suggestion
    User get(Long id);
```
again, uniform method names everywhere

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/mappers/UserMapper.java
> +    public User getUserFromDto(UserRequestDto userRequestDto) {
where do you use this method?

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/mappers/ShoppingCartMapper.java
> +    private UserService userService;
do you use this dependency?

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/mappers/OrderMapper.java
> +    private UserService userService;
same

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/model/dto/OrderResponseDto.java
> +    private String orderData;
```suggestion
    private String orderDate;
```

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/mappers/OrderMapper.java
> +                .map(x -> x.getId())
`x` is not informative

2020-10-27 14:18 UTC, KseniiaMakarova commented on src/main/java/com/cinema/shop/mappers/ShoppingCartMapper.java
> +                .map(x -> x.getId())
same

2020-10-27 14:56 UTC, margarita-ignatieva commented on src/main/java/com/cinema/shop/service/UserService.java
> +    User getById(Long id);
changed to getById everywhere

2020-10-27 14:56 UTC, margarita-ignatieva commented on src/main/java/com/cinema/shop/mappers/ShoppingCartMapper.java
> +    private UserService userService;
no

2020-10-27 14:56 UTC, margarita-ignatieva commented on src/main/java/com/cinema/shop/model/dto/OrderResponseDto.java
> +    private String orderData;
done

2020-10-27 14:56 UTC, margarita-ignatieva commented on src/main/java/com/cinema/shop/mappers/ShoppingCartMapper.java
> +                .map(x -> x.getId())
done

2020-10-27 14:57 UTC, margarita-ignatieva commented on src/main/java/com/cinema/shop/service/TicketService.java
> +public interface TicketService {
no, maybe, not now

2020-10-27 14:57 UTC, margarita-ignatieva commented on src/main/java/com/cinema/shop/model/dto/UserResponseDto.java
> +    private String password;
ok

2020-10-27 14:57 UTC, margarita-ignatieva commented on src/main/java/com/cinema/shop/model/dto/ShoppingCartResponseDto.java
> +    private Long userId;
yes

2020-10-27 14:57 UTC, margarita-ignatieva commented on src/main/java/com/cinema/shop/dao/TicketDao.java
> +    Ticket getById(Long id);
nope

2020-10-27 14:58 UTC, margarita-ignatieva commented on src/main/java/com/cinema/shop/controllers/OrderController.java
> +    private OrderMapper orderMapper;
done

2020-10-27 14:58 UTC, margarita-ignatieva commented on src/main/java/com/cinema/shop/controllers/UserController.java
> +    private UserMapper userMapper;
done

2020-10-28 07:33 UTC, KseniiaMakarova approved these changes
let's remove `getUserFromDto()` method from UserMapper - I believe you do not use it?

2020-10-28 10:54 UTC, margarita-ignatieva commented
> let's remove `getUserFromDto()` method from UserMapper - I believe you do not use it?

no, don't

2020-10-28 11:02 UTC, merged